# Generated by Django 5.1.4 on 2025-03-02 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='product',
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='a', editable=False, max_length=255, unique=True, verbose_name='slug'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(related_name='%(class)s_category', to='product.category', verbose_name='category'),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='s', editable=False, max_length=255, unique=True, verbose_name='slug'),
            preserve_default=False,
        ),
    ]
