# Generated by Django 5.1.4 on 2025-03-03 18:19

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import nep_shop.utils
from django.db import migrations, models
from product.models import Product


class Migration(migrations.Migration):

    dependencies = [
        ('auth_profile', '0002_buyer'),
        ('product', '0003_remove_category_product_category_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='product',
            field=models.ForeignKey(default=Product.objects.get(name="Laptop").id, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_product', to='product.product', verbose_name='product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_seller', to='auth_profile.seller', verbose_name='seller'),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(upload_to=nep_shop.utils.get_image_upload_path, verbose_name='thumbnail'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to=nep_shop.utils.get_image_upload_path, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_product', to='product.product', verbose_name='product'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_buyer', to='auth_profile.buyer', verbose_name='buyer'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='rating'),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('buyer', 'product')},
        ),
    ]
